[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["alanzcc <alanzcc1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
selenium = "^4.20.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
